use std::str::FromStr;
use strum_macros::Display;

#[non_exhaustive]
#[derive(Display)]
enum SubTypes {
    Advisor,
    Aetherborn,
    Ally,
    Angel,
    Antelope,
    Ape,
    Archer,
    Archon,
    Army,
    Artificer,
    Assassin,
    AssemblyWorker,
    Atog,
    Aurochs,
    Avatar,
    Azra,
    Badger,
    Barbarian,
    Bard,
    Basilisk,
    Bat,
    Bear,
    Beast,
    Beeble,
    Beholder,
    Berserker,
    Bird,
    Blinkmoth,
    Boar,
    Bringer,
    Brushwagg,
    Camarid,
    Camel,
    Caribou,
    Carrier,
    Cat,
    Centaur,
    Cephalid,
    Chimera,
    Citizen,
    Cleric,
    Cockatrice,
    Construct,
    Coward,
    Crab,
    Crocodile,
    Cyclops,
    Dauthi,
    Demigod,
    Demon,
    Deserter,
    Devil,
    Dinosaur,
    Djinn,
    Dog,
    Dragon,
    Drake,
    Dreadnought,
    Drone,
    Druid,
    Dryad,
    Dwarf,
    Efreet,
    Egg,
    Elder,
    Eldrazi,
    Elemental,
    Elephant,
    Elf,
    Elk,
    Eye,
    Faerie,
    Ferret,
    Fish,
    Flagbearer,
    Fox,
    Fractal,
    Frog,
    Fungus,
    Gargoyle,
    Germ,
    Giant,
    Gnoll,
    Gnome,
    Goat,
    Goblin,
    God,
    Golem,
    Gorgon,
    Graveborn,
    Gremlin,
    Griffin,
    Hag,
    Halfling,
    Hamster,
    Harpy,
    Hellion,
    Hippo,
    Hippogriff,
    Homarid,
    Homunculus,
    Horror,
    Horse,
    Human,
    Hydra,
    Hyena,
    Illusion,
    Imp,
    Incarnation,
    Inkling,
    Insect,
    Jackal,
    Jellyfish,
    Juggernaut,
    Kavu,
    Kirin,
    Kithkin,
    Knight,
    Kobold,
    Kor,
    Kraken,
    Lamia,
    Lammasu,
    Leech,
    Leviathan,
    Lhurgoyf,
    Licid,
    Lizard,
    Manticore,
    Masticore,
    Mercenary,
    Merfolk,
    Metathran,
    Minion,
    Minotaur,
    Mole,
    Monger,
    Mongoose,
    Monk,
    Monkey,
    Moonfolk,
    Mouse,
    Mutant,
    Myr,
    Mystic,
    Naga,
    Nautilus,
    Nephilim,
    Nightmare,
    Nightstalker,
    Ninja,
    Noble,
    Noggle,
    Nomad,
    Nymph,
    Octopus,
    Ogre,
    Ooze,
    Orb,
    Orc,
    Orgg,
    Otter,
    Ouphe,
    Ox,
    Oyster,
    Pangolin,
    Peasant,
    Pegasus,
    Pentavite,
    Pest,
    Phelddagrif,
    Phoenix,
    Phyrexian,
    Pilot,
    Pincher,
    Pirate,
    Plant,
    Praetor,
    Prism,
    Processor,
    Rabbit,
    Ranger,
    Rat,
    Rebel,
    Reflection,
    Rhino,
    Rigger,
    Rogue,
    Sable,
    Salamander,
    Samurai,
    Sand,
    Saproling,
    Satyr,
    Scarecrow,
    Scion,
    Scorpion,
    Scout,
    Sculpture,
    Serf,
    Serpent,
    Servo,
    Shade,
    Shaman,
    Shapeshifter,
    Shark,
    Sheep,
    Siren,
    Skeleton,
    Slith,
    Sliver,
    Slug,
    Snake,
    Soldier,
    Soltari,
    Spawn,
    Specter,
    Spellshaper,
    Sphinx,
    Spider,
    Spike,
    Spirit,
    Splinter,
    Sponge,
    Squid,
    Squirrel,
    Starfish,
    Surrakar,
    Survivor,
    Tentacle,
    Tetravite,
    Thalakos,
    Thopter,
    Thrull,
    Tiefling,
    Treefolk,
    Trilobite,
    Triskelavite,
    Troll,
    Turtle,
    Unicorn,
    Vampire,
    Vedalken,
    Viashino,
    Volver,
    Wall,
    Warlock,
    Warrior,
    Weird,
    Werewolf,
    Whale,
    Wizard,
    Wolf,
    Wolverine,
    Wombat,
    Worm,
    Wraith,
    Wurm,
    Yeti,
    Zombie,
    Zubera,
    Ajani,
    Aminatou,
    Angrath,
    Arlinn,
    Ashiok,
    Bahamut,
    Basri,
    Bolas,
    Calix,
    Chandra,
    Dack,
    Dakkon,
    Daretti,
    Davriel,
    Dihada,
    Domri,
    Dovin,
    Ellywick,
    Elspeth,
    Estrid,
    Freyalise,
    Garruk,
    Gideon,
    Grist,
    Huatli,
    Jace,
    Jaya,
    Jeska,
    Karn,
    Kasmina,
    Kaya,
    Kiora,
    Koth,
    Liliana,
    Lolth,
    Lukka,
    Mordenkainen,
    Nahiri,
    Narset,
    Niko,
    Nissa,
    Nixilis,
    Oko,
    Ral,
    Rowan,
    Saheeli,
    Samut,
    Sarkhan,
    Serra,
    Sorin,
    Szat,
    Tamiyo,
    Teferi,
    Teyo,
    Tezzeret,
    Tibalt,
    Tyvar,
    Ugin,
    Venser,
    Vivien,
    Vraska,
    Will,
    Windgrace,
    Wrenn,
    Xenagos,
    Yanggu,
    Yanling,
    Zariel,
    Desert,
    Forest,
    Gate,
    Island,
    Lair,
    Locus,
    Mine,
    Mountain,
    Plains,
    PowerPlant,
    Swamp,
    Tower,
    Urzas,
    Cartouche,
    Class,
    Curse,
    Rune,
    Saga,
    Shard,
    Shrine,
    Clue,
    Contraption,
    Equipment,
    Food,
    Fortification,
    Gold,
    Treasure,
    Vehicle,
    Adventure,
    Arcane,
    Lesson,
    Trap,
}
impl FromStr for SubTypes {
    type Err = ();

    fn from_str(input: &str) -> Result<SubTypes, Self::Err> {
        match input {
            "Advisor" => Ok(SubTypes::Advisor),
            "Aetherborn" => Ok(SubTypes::Aetherborn),
            "Ally" => Ok(SubTypes::Ally),
            "Angel" => Ok(SubTypes::Angel),
            "Antelope" => Ok(SubTypes::Antelope),
            "Ape" => Ok(SubTypes::Ape),
            "Archer" => Ok(SubTypes::Archer),
            "Archon" => Ok(SubTypes::Archon),
            "Army" => Ok(SubTypes::Army),
            "Artificer" => Ok(SubTypes::Artificer),
            "Assassin" => Ok(SubTypes::Assassin),
            "AssemblyWorker" => Ok(SubTypes::AssemblyWorker),
            "Assembly_Worker" => Ok(SubTypes::AssemblyWorker),
            "Assembly-Worker" => Ok(SubTypes::AssemblyWorker),
            "Atog" => Ok(SubTypes::Atog),
            "Aurochs" => Ok(SubTypes::Aurochs),
            "Avatar" => Ok(SubTypes::Avatar),
            "Azra" => Ok(SubTypes::Azra),
            "Badger" => Ok(SubTypes::Badger),
            "Barbarian" => Ok(SubTypes::Barbarian),
            "Bard" => Ok(SubTypes::Bard),
            "Basilisk" => Ok(SubTypes::Basilisk),
            "Bat" => Ok(SubTypes::Bat),
            "Bear" => Ok(SubTypes::Bear),
            "Beast" => Ok(SubTypes::Beast),
            "Beeble" => Ok(SubTypes::Beeble),
            "Beholder" => Ok(SubTypes::Beholder),
            "Berserker" => Ok(SubTypes::Berserker),
            "Bird" => Ok(SubTypes::Bird),
            "Blinkmoth" => Ok(SubTypes::Blinkmoth),
            "Boar" => Ok(SubTypes::Boar),
            "Bringer" => Ok(SubTypes::Bringer),
            "Brushwagg" => Ok(SubTypes::Brushwagg),
            "Camarid" => Ok(SubTypes::Camarid),
            "Camel" => Ok(SubTypes::Camel),
            "Caribou" => Ok(SubTypes::Caribou),
            "Carrier" => Ok(SubTypes::Carrier),
            "Cat" => Ok(SubTypes::Cat),
            "Centaur" => Ok(SubTypes::Centaur),
            "Cephalid" => Ok(SubTypes::Cephalid),
            "Chimera" => Ok(SubTypes::Chimera),
            "Citizen" => Ok(SubTypes::Citizen),
            "Cleric" => Ok(SubTypes::Cleric),
            "Cockatrice" => Ok(SubTypes::Cockatrice),
            "Construct" => Ok(SubTypes::Construct),
            "Coward" => Ok(SubTypes::Coward),
            "Crab" => Ok(SubTypes::Crab),
            "Crocodile" => Ok(SubTypes::Crocodile),
            "Cyclops" => Ok(SubTypes::Cyclops),
            "Dauthi" => Ok(SubTypes::Dauthi),
            "Demigod" => Ok(SubTypes::Demigod),
            "Demon" => Ok(SubTypes::Demon),
            "Deserter" => Ok(SubTypes::Deserter),
            "Devil" => Ok(SubTypes::Devil),
            "Dinosaur" => Ok(SubTypes::Dinosaur),
            "Djinn" => Ok(SubTypes::Djinn),
            "Dog" => Ok(SubTypes::Dog),
            "Dragon" => Ok(SubTypes::Dragon),
            "Drake" => Ok(SubTypes::Drake),
            "Dreadnought" => Ok(SubTypes::Dreadnought),
            "Drone" => Ok(SubTypes::Drone),
            "Druid" => Ok(SubTypes::Druid),
            "Dryad" => Ok(SubTypes::Dryad),
            "Dwarf" => Ok(SubTypes::Dwarf),
            "Efreet" => Ok(SubTypes::Efreet),
            "Egg" => Ok(SubTypes::Egg),
            "Elder" => Ok(SubTypes::Elder),
            "Eldrazi" => Ok(SubTypes::Eldrazi),
            "Elemental" => Ok(SubTypes::Elemental),
            "Elephant" => Ok(SubTypes::Elephant),
            "Elf" => Ok(SubTypes::Elf),
            "Elk" => Ok(SubTypes::Elk),
            "Eye" => Ok(SubTypes::Eye),
            "Faerie" => Ok(SubTypes::Faerie),
            "Ferret" => Ok(SubTypes::Ferret),
            "Fish" => Ok(SubTypes::Fish),
            "Flagbearer" => Ok(SubTypes::Flagbearer),
            "Fox" => Ok(SubTypes::Fox),
            "Fractal" => Ok(SubTypes::Fractal),
            "Frog" => Ok(SubTypes::Frog),
            "Fungus" => Ok(SubTypes::Fungus),
            "Gargoyle" => Ok(SubTypes::Gargoyle),
            "Germ" => Ok(SubTypes::Germ),
            "Giant" => Ok(SubTypes::Giant),
            "Gnoll" => Ok(SubTypes::Gnoll),
            "Gnome" => Ok(SubTypes::Gnome),
            "Goat" => Ok(SubTypes::Goat),
            "Goblin" => Ok(SubTypes::Goblin),
            "God" => Ok(SubTypes::God),
            "Golem" => Ok(SubTypes::Golem),
            "Gorgon" => Ok(SubTypes::Gorgon),
            "Graveborn" => Ok(SubTypes::Graveborn),
            "Gremlin" => Ok(SubTypes::Gremlin),
            "Griffin" => Ok(SubTypes::Griffin),
            "Hag" => Ok(SubTypes::Hag),
            "Halfling" => Ok(SubTypes::Halfling),
            "Hamster" => Ok(SubTypes::Hamster),
            "Harpy" => Ok(SubTypes::Harpy),
            "Hellion" => Ok(SubTypes::Hellion),
            "Hippo" => Ok(SubTypes::Hippo),
            "Hippogriff" => Ok(SubTypes::Hippogriff),
            "Homarid" => Ok(SubTypes::Homarid),
            "Homunculus" => Ok(SubTypes::Homunculus),
            "Horror" => Ok(SubTypes::Horror),
            "Horse" => Ok(SubTypes::Horse),
            "Human" => Ok(SubTypes::Human),
            "Hydra" => Ok(SubTypes::Hydra),
            "Hyena" => Ok(SubTypes::Hyena),
            "Illusion" => Ok(SubTypes::Illusion),
            "Imp" => Ok(SubTypes::Imp),
            "Incarnation" => Ok(SubTypes::Incarnation),
            "Inkling" => Ok(SubTypes::Inkling),
            "Insect" => Ok(SubTypes::Insect),
            "Jackal" => Ok(SubTypes::Jackal),
            "Jellyfish" => Ok(SubTypes::Jellyfish),
            "Juggernaut" => Ok(SubTypes::Juggernaut),
            "Kavu" => Ok(SubTypes::Kavu),
            "Kirin" => Ok(SubTypes::Kirin),
            "Kithkin" => Ok(SubTypes::Kithkin),
            "Knight" => Ok(SubTypes::Knight),
            "Kobold" => Ok(SubTypes::Kobold),
            "Kor" => Ok(SubTypes::Kor),
            "Kraken" => Ok(SubTypes::Kraken),
            "Lamia" => Ok(SubTypes::Lamia),
            "Lammasu" => Ok(SubTypes::Lammasu),
            "Leech" => Ok(SubTypes::Leech),
            "Leviathan" => Ok(SubTypes::Leviathan),
            "Lhurgoyf" => Ok(SubTypes::Lhurgoyf),
            "Licid" => Ok(SubTypes::Licid),
            "Lizard" => Ok(SubTypes::Lizard),
            "Manticore" => Ok(SubTypes::Manticore),
            "Masticore" => Ok(SubTypes::Masticore),
            "Mercenary" => Ok(SubTypes::Mercenary),
            "Merfolk" => Ok(SubTypes::Merfolk),
            "Metathran" => Ok(SubTypes::Metathran),
            "Minion" => Ok(SubTypes::Minion),
            "Minotaur" => Ok(SubTypes::Minotaur),
            "Mole" => Ok(SubTypes::Mole),
            "Monger" => Ok(SubTypes::Monger),
            "Mongoose" => Ok(SubTypes::Mongoose),
            "Monk" => Ok(SubTypes::Monk),
            "Monkey" => Ok(SubTypes::Monkey),
            "Moonfolk" => Ok(SubTypes::Moonfolk),
            "Mouse" => Ok(SubTypes::Mouse),
            "Mutant" => Ok(SubTypes::Mutant),
            "Myr" => Ok(SubTypes::Myr),
            "Mystic" => Ok(SubTypes::Mystic),
            "Naga" => Ok(SubTypes::Naga),
            "Nautilus" => Ok(SubTypes::Nautilus),
            "Nephilim" => Ok(SubTypes::Nephilim),
            "Nightmare" => Ok(SubTypes::Nightmare),
            "Nightstalker" => Ok(SubTypes::Nightstalker),
            "Ninja" => Ok(SubTypes::Ninja),
            "Noble" => Ok(SubTypes::Noble),
            "Noggle" => Ok(SubTypes::Noggle),
            "Nomad" => Ok(SubTypes::Nomad),
            "Nymph" => Ok(SubTypes::Nymph),
            "Octopus" => Ok(SubTypes::Octopus),
            "Ogre" => Ok(SubTypes::Ogre),
            "Ooze" => Ok(SubTypes::Ooze),
            "Orb" => Ok(SubTypes::Orb),
            "Orc" => Ok(SubTypes::Orc),
            "Orgg" => Ok(SubTypes::Orgg),
            "Otter" => Ok(SubTypes::Otter),
            "Ouphe" => Ok(SubTypes::Ouphe),
            "Ox" => Ok(SubTypes::Ox),
            "Oyster" => Ok(SubTypes::Oyster),
            "Pangolin" => Ok(SubTypes::Pangolin),
            "Peasant" => Ok(SubTypes::Peasant),
            "Pegasus" => Ok(SubTypes::Pegasus),
            "Pentavite" => Ok(SubTypes::Pentavite),
            "Pest" => Ok(SubTypes::Pest),
            "Phelddagrif" => Ok(SubTypes::Phelddagrif),
            "Phoenix" => Ok(SubTypes::Phoenix),
            "Phyrexian" => Ok(SubTypes::Phyrexian),
            "Pilot" => Ok(SubTypes::Pilot),
            "Pincher" => Ok(SubTypes::Pincher),
            "Pirate" => Ok(SubTypes::Pirate),
            "Plant" => Ok(SubTypes::Plant),
            "Praetor" => Ok(SubTypes::Praetor),
            "Prism" => Ok(SubTypes::Prism),
            "Processor" => Ok(SubTypes::Processor),
            "Rabbit" => Ok(SubTypes::Rabbit),
            "Ranger" => Ok(SubTypes::Ranger),
            "Rat" => Ok(SubTypes::Rat),
            "Rebel" => Ok(SubTypes::Rebel),
            "Reflection" => Ok(SubTypes::Reflection),
            "Rhino" => Ok(SubTypes::Rhino),
            "Rigger" => Ok(SubTypes::Rigger),
            "Rogue" => Ok(SubTypes::Rogue),
            "Sable" => Ok(SubTypes::Sable),
            "Salamander" => Ok(SubTypes::Salamander),
            "Samurai" => Ok(SubTypes::Samurai),
            "Sand" => Ok(SubTypes::Sand),
            "Saproling" => Ok(SubTypes::Saproling),
            "Satyr" => Ok(SubTypes::Satyr),
            "Scarecrow" => Ok(SubTypes::Scarecrow),
            "Scion" => Ok(SubTypes::Scion),
            "Scorpion" => Ok(SubTypes::Scorpion),
            "Scout" => Ok(SubTypes::Scout),
            "Sculpture" => Ok(SubTypes::Sculpture),
            "Serf" => Ok(SubTypes::Serf),
            "Serpent" => Ok(SubTypes::Serpent),
            "Servo" => Ok(SubTypes::Servo),
            "Shade" => Ok(SubTypes::Shade),
            "Shaman" => Ok(SubTypes::Shaman),
            "Shapeshifter" => Ok(SubTypes::Shapeshifter),
            "Shark" => Ok(SubTypes::Shark),
            "Sheep" => Ok(SubTypes::Sheep),
            "Siren" => Ok(SubTypes::Siren),
            "Skeleton" => Ok(SubTypes::Skeleton),
            "Slith" => Ok(SubTypes::Slith),
            "Sliver" => Ok(SubTypes::Sliver),
            "Slug" => Ok(SubTypes::Slug),
            "Snake" => Ok(SubTypes::Snake),
            "Soldier" => Ok(SubTypes::Soldier),
            "Soltari" => Ok(SubTypes::Soltari),
            "Spawn" => Ok(SubTypes::Spawn),
            "Specter" => Ok(SubTypes::Specter),
            "Spellshaper" => Ok(SubTypes::Spellshaper),
            "Sphinx" => Ok(SubTypes::Sphinx),
            "Spider" => Ok(SubTypes::Spider),
            "Spike" => Ok(SubTypes::Spike),
            "Spirit" => Ok(SubTypes::Spirit),
            "Splinter" => Ok(SubTypes::Splinter),
            "Sponge" => Ok(SubTypes::Sponge),
            "Squid" => Ok(SubTypes::Squid),
            "Squirrel" => Ok(SubTypes::Squirrel),
            "Starfish" => Ok(SubTypes::Starfish),
            "Surrakar" => Ok(SubTypes::Surrakar),
            "Survivor" => Ok(SubTypes::Survivor),
            "Tentacle" => Ok(SubTypes::Tentacle),
            "Tetravite" => Ok(SubTypes::Tetravite),
            "Thalakos" => Ok(SubTypes::Thalakos),
            "Thopter" => Ok(SubTypes::Thopter),
            "Thrull" => Ok(SubTypes::Thrull),
            "Tiefling" => Ok(SubTypes::Tiefling),
            "Treefolk" => Ok(SubTypes::Treefolk),
            "Trilobite" => Ok(SubTypes::Trilobite),
            "Triskelavite" => Ok(SubTypes::Triskelavite),
            "Troll" => Ok(SubTypes::Troll),
            "Turtle" => Ok(SubTypes::Turtle),
            "Unicorn" => Ok(SubTypes::Unicorn),
            "Vampire" => Ok(SubTypes::Vampire),
            "Vedalken" => Ok(SubTypes::Vedalken),
            "Viashino" => Ok(SubTypes::Viashino),
            "Volver" => Ok(SubTypes::Volver),
            "Wall" => Ok(SubTypes::Wall),
            "Warlock" => Ok(SubTypes::Warlock),
            "Warrior" => Ok(SubTypes::Warrior),
            "Weird" => Ok(SubTypes::Weird),
            "Werewolf" => Ok(SubTypes::Werewolf),
            "Whale" => Ok(SubTypes::Whale),
            "Wizard" => Ok(SubTypes::Wizard),
            "Wolf" => Ok(SubTypes::Wolf),
            "Wolverine" => Ok(SubTypes::Wolverine),
            "Wombat" => Ok(SubTypes::Wombat),
            "Worm" => Ok(SubTypes::Worm),
            "Wraith" => Ok(SubTypes::Wraith),
            "Wurm" => Ok(SubTypes::Wurm),
            "Yeti" => Ok(SubTypes::Yeti),
            "Zombie" => Ok(SubTypes::Zombie),
            "Zubera" => Ok(SubTypes::Zubera),
            "Ajani" => Ok(SubTypes::Ajani),
            "Aminatou" => Ok(SubTypes::Aminatou),
            "Angrath" => Ok(SubTypes::Angrath),
            "Arlinn" => Ok(SubTypes::Arlinn),
            "Ashiok" => Ok(SubTypes::Ashiok),
            "Bahamut" => Ok(SubTypes::Bahamut),
            "Basri" => Ok(SubTypes::Basri),
            "Bolas" => Ok(SubTypes::Bolas),
            "Calix" => Ok(SubTypes::Calix),
            "Chandra" => Ok(SubTypes::Chandra),
            "Dack" => Ok(SubTypes::Dack),
            "Dakkon" => Ok(SubTypes::Dakkon),
            "Daretti" => Ok(SubTypes::Daretti),
            "Davriel" => Ok(SubTypes::Davriel),
            "Dihada" => Ok(SubTypes::Dihada),
            "Domri" => Ok(SubTypes::Domri),
            "Dovin" => Ok(SubTypes::Dovin),
            "Ellywick" => Ok(SubTypes::Ellywick),
            "Elspeth" => Ok(SubTypes::Elspeth),
            "Estrid" => Ok(SubTypes::Estrid),
            "Freyalise" => Ok(SubTypes::Freyalise),
            "Garruk" => Ok(SubTypes::Garruk),
            "Gideon" => Ok(SubTypes::Gideon),
            "Grist" => Ok(SubTypes::Grist),
            "Huatli" => Ok(SubTypes::Huatli),
            "Jace" => Ok(SubTypes::Jace),
            "Jaya" => Ok(SubTypes::Jaya),
            "Jeska" => Ok(SubTypes::Jeska),
            "Karn" => Ok(SubTypes::Karn),
            "Kasmina" => Ok(SubTypes::Kasmina),
            "Kaya" => Ok(SubTypes::Kaya),
            "Kiora" => Ok(SubTypes::Kiora),
            "Koth" => Ok(SubTypes::Koth),
            "Liliana" => Ok(SubTypes::Liliana),
            "Lolth" => Ok(SubTypes::Lolth),
            "Lukka" => Ok(SubTypes::Lukka),
            "Mordenkainen" => Ok(SubTypes::Mordenkainen),
            "Nahiri" => Ok(SubTypes::Nahiri),
            "Narset" => Ok(SubTypes::Narset),
            "Niko" => Ok(SubTypes::Niko),
            "Nissa" => Ok(SubTypes::Nissa),
            "Nixilis" => Ok(SubTypes::Nixilis),
            "Oko" => Ok(SubTypes::Oko),
            "Ral" => Ok(SubTypes::Ral),
            "Rowan" => Ok(SubTypes::Rowan),
            "Saheeli" => Ok(SubTypes::Saheeli),
            "Samut" => Ok(SubTypes::Samut),
            "Sarkhan" => Ok(SubTypes::Sarkhan),
            "Serra" => Ok(SubTypes::Serra),
            "Sorin" => Ok(SubTypes::Sorin),
            "Szat" => Ok(SubTypes::Szat),
            "Tamiyo" => Ok(SubTypes::Tamiyo),
            "Teferi" => Ok(SubTypes::Teferi),
            "Teyo" => Ok(SubTypes::Teyo),
            "Tezzeret" => Ok(SubTypes::Tezzeret),
            "Tibalt" => Ok(SubTypes::Tibalt),
            "Tyvar" => Ok(SubTypes::Tyvar),
            "Ugin" => Ok(SubTypes::Ugin),
            "Venser" => Ok(SubTypes::Venser),
            "Vivien" => Ok(SubTypes::Vivien),
            "Vraska" => Ok(SubTypes::Vraska),
            "Will" => Ok(SubTypes::Will),
            "Windgrace" => Ok(SubTypes::Windgrace),
            "Wrenn" => Ok(SubTypes::Wrenn),
            "Xenagos" => Ok(SubTypes::Xenagos),
            "Yanggu" => Ok(SubTypes::Yanggu),
            "Yanling" => Ok(SubTypes::Yanling),
            "Zariel" => Ok(SubTypes::Zariel),
            "Desert" => Ok(SubTypes::Desert),
            "Forest" => Ok(SubTypes::Forest),
            "Gate" => Ok(SubTypes::Gate),
            "Island" => Ok(SubTypes::Island),
            "Lair" => Ok(SubTypes::Lair),
            "Locus" => Ok(SubTypes::Locus),
            "Mine" => Ok(SubTypes::Mine),
            "Mountain" => Ok(SubTypes::Mountain),
            "Plains" => Ok(SubTypes::Plains),
            "PowerPlant" => Ok(SubTypes::PowerPlant),
            "Power_Plant" => Ok(SubTypes::PowerPlant),
            "Power-Plant" => Ok(SubTypes::PowerPlant),
            "Swamp" => Ok(SubTypes::Swamp),
            "Tower" => Ok(SubTypes::Tower),
            "Urzas" => Ok(SubTypes::Urzas),
            "Cartouche" => Ok(SubTypes::Cartouche),
            "Class" => Ok(SubTypes::Class),
            "Curse" => Ok(SubTypes::Curse),
            "Rune" => Ok(SubTypes::Rune),
            "Saga" => Ok(SubTypes::Saga),
            "Shard" => Ok(SubTypes::Shard),
            "Shrine" => Ok(SubTypes::Shrine),
            "Clue" => Ok(SubTypes::Clue),
            "Contraption" => Ok(SubTypes::Contraption),
            "Equipment" => Ok(SubTypes::Equipment),
            "Food" => Ok(SubTypes::Food),
            "Fortification" => Ok(SubTypes::Fortification),
            "Gold" => Ok(SubTypes::Gold),
            "Treasure" => Ok(SubTypes::Treasure),
            "Vehicle" => Ok(SubTypes::Vehicle),
            "Adventure" => Ok(SubTypes::Adventure),
            "Arcane" => Ok(SubTypes::Arcane),
            "Lesson" => Ok(SubTypes::Lesson),
            "Trap" => Ok(SubTypes::Trap),
            _ => Err(()),
        }
    }
}
